### ISSUE TITLE
Recent 28.2.1 release broke menuTabs

### ISSUE THREAD

**Issue by whutchtwo** [ag-grid/ag-grid#5744]
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

In 28.2.0 release menuTabs type was menuTabs?: string[];
In 28.2.1 then menuTabs type is ColumnMenuTab = 'filterMenuTab' | 'generalMenuTab' | 'columnsMenuTab';

We had our package.json for ag-grid configured as ~28.2.0 so we started to have build errors from this patch update because we can no longer use these types for menuTabs:
          'copyWithHeaders',
          'csvExport',
          'autoSizeAll',
          'autoSizeThis',
          'resetColumns'

The ag-grid documentation does not show to implement this any differently.

**Comment by StephenCooper** [comment]
Hi,

Those options should not be passed to `menuTabs`, if you do that you should see the following warning in your console when the column menu is opened. 

```ts
AG Grid: Trying to render an invalid menu item 'copyWithHeaders'. Check that your 'menuTabs' contains one of [generalMenuTab,filterMenuTab,columnsMenuTab]
```
As can be seen here: https://plnkr.co/edit/W1fFyWtfDTOIntEP?open=main.ts

Those items should be passed to the [getMainMenuItems](https://ag-grid.com/javascript-data-grid/column-menu/#customising-the-general-menu-tab) callback as part of gridOptions.

If you still think this is a bug please update the plunker here to show the issue.

**Comment by whutchtwo** [comment]
Ok, I will check with the team that implemented it. I was under the assumption it was previously working. We will make the changes you suggest.

**Comment by dfravel** [comment]
jumping in on this thread. I believe there may be a problem. 

in 28.2.0, this syntax worked:

```
menuTabs: ["filterMenuTab", "generalMenuTab"]
```

and now in 28.2.1, I receive an error that the types aren't compatible. 

```
Type '{ flex: number; filter: boolean; sortable: boolean; autoHeight: boolean; resizable: boolean; enableRowGroup: boolean; enablePivot: boolean; menuTabs: string[]; }' is not assignable to type 'ColDef<any>'.
  Types of property 'menuTabs' are incompatible.
    Type 'string[]' is not assignable to type 'ColumnMenuTab[]'.
      Type 'string' is not assignable to type 'ColumnMenuTab'.
```

I'm happy to open a new issue if that's the appropriate step to take

**Comment by dfravel** [comment]
@StephenCooper - I'll see what I can do about a demo, but if it helps, I create an object for defaultColDefs and use that for the GridOptions. 

Here's my global defaultColDefs. This syntax will now build, but it no longer seems to work:

```
const defaultColDefs = {
  flex: 1,
  filter: true,
  sortable: true,
  autoHeight: true,
  resizable: true,
  enableRowGroup: true,
  enablePivot: false,
  getMainMenuItems: () => {
    return ["filterMenuTab", "generalMenuTab"];
  },
  // menuTabs: ["filterMenuTab", "generalMenuTab"],
};
```

I've commented out the last line above and replaced it with a call to getMainMenuItems. This just "broke" this morning when I upgraded locally to 28.2.1. I'm using 28.2.0 in production and it's working as expected.

**Comment by StephenCooper** [comment]
First issue is that `getMainMenuItems` is a callback on the `GridOptions` see [here](https://ag-grid.com/javascript-data-grid/grid-options/#reference-accessories-getMainMenuItems) so that will error as it is not a valid property of the `ColDef`.

I have no issue with the last line in 28.2.1 and can have `menuTabs: ["filterMenuTab", "generalMenuTab"],` with no compilation errors.

**Comment by dfravel** [comment]
thanks for the followup @StephenCooper! I wonder if this is an issue with one of my dependencies/linters? I was able to get this to build and work by updating my **defaultColDefs** like so:

```
const defaultColDefs = {
  flex: 1,
  filter: true,
  sortable: true,
  autoHeight: true,
  resizable: true,
  enableRowGroup: true,
  enablePivot: false,
  menuTabs: ["filterMenuTab", "generalMenuTab"] as ColumnMenuTab[],
};
```

as long as I'm casting menuTabs as ColumnMenuTab[] it works.  It's possible this was a result of 28.2.1, but if it's working for you, it's more likely something with vue-tsc/volar on my end and was just a coincidence that I updated to 28.2.1.
