### ISSUE TITLE
Modules not assignable to interface Module

### ISSUE THREAD

**Issue by Koslun** [ag-grid/ag-grid#4320]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of ag-Grid**

We have a valid paid license of ag-Grid and will send a separate request through the official customer support system if things aren't solved through this issue. From our perspective communicating openly in this Github issue is preferable.

**Providing a Reproducible Scenario**

`Module` type no longer overlaps with the various modules in ag-grid from both community and enterprise modules. Causing two issues:
1. Previous explicit typing no longer work. Quick-fix: avoid explicit typing.
2. Implicit typing of Angular modules no longer work when using the new default compiler Ivy (default since version 11). Quick-fix: explicitly type the module arrays to `any[]`.

I.e. this will generate a Type Error:
```TypeScript
import { Module } from '@ag-grid-community/core';

import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';
import { InfiniteRowModelModule } from '@ag-grid-community/infinite-row-model';

import { ClipboardModule } from '@ag-grid-enterprise/clipboard';
import { MenuModule } from '@ag-grid-enterprise/menu';
import { SetFilterModule } from '@ag-grid-enterprise/set-filter';
import { StatusBarModule } from '@ag-grid-enterprise/status-bar';

/**
 * The standard ag-grid modules used across the app.
 */
export const agGridStdModules: Module[] = [
  ClientSideRowModelModule,
  InfiniteRowModelModule,
  MenuModule,
  ClipboardModule,
  SetFilterModule,
  StatusBarModule,
];
```

More crucially directly sending above array as input to the official Angular component doesn't work either:

```HTML
<ag-grid-angular
  <!-- other attributes omitted -->
  [modules]="modules"
></ag-grid-angular>
```
I.e. when picking modules to load in Angular there appears to always be a TypeError: https://www.ag-grid.com/documentation/angular/modules/#installing-ag-grid-modules

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Above code for Angular generates errors stating that the Modules do not match:

```
error TS2322: Type 'import("/MY_REPO/node_modules/@ag-grid-community/client-side-row-model/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iModule").Module[]' is not assignable to type 'import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iModule").Module[]'
```

Additionally when explicitly typing the modules array each module in the array will generate an error stating that something is missing, example for `ClientSideRowModelModule`:
```
Type 'import("/MY_REPO/node_modules/@ag-grid-community/client-side-row-model/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iModule").Module' is not assignable to type 'import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iModule").Module'.
  Types of property 'userComponents' are incompatible.
    Type '{ componentName: string; componentClass: import("/MY_REPO/node_modules/@ag-grid-community/client-side-row-model/node_modules/@ag-grid-community/core/dist/cjs/components/framework/userComponentRegistry").AgGridRegisteredComponentInput<import("/Users/koslun/repos/normative/normati...' is not assignable to type '{ componentName: string; componentClass: import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/components/framework/userComponentRegistry").AgGridRegisteredComponentInput<import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cj...'.
      Type '{ componentName: string; componentClass: import("/MY_REPO/node_modules/@ag-grid-community/client-side-row-model/node_modules/@ag-grid-community/core/dist/cjs/components/framework/userComponentRegistry").AgGridRegisteredComponentInput<import("/Users/koslun/repos/normative/normati...' is not assignable to type '{ componentName: string; componentClass: import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/components/framework/userComponentRegistry").AgGridRegisteredComponentInput<import("/MYREPO/node_modules/@ag-grid-community/core/dist/cj...'.
        Types of property 'componentClass' are incompatible.
          Type 'import("/MY_REPO/node_modules/@ag-grid-community/client-side-row-model/node_modules/@ag-grid-community/core/dist/cjs/components/framework/userComponentRegistry").AgGridRegisteredComponentInput<import("/MY_REPO/node_modules/@ag-grid-community...' is not assignable to type 'import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/components/framework/userComponentRegistry").AgGridRegisteredComponentInput<import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iComponent").IComponent<any>>'.
            Type 'new () => IComponent<any>' is not assignable to type 'AgGridRegisteredComponentInput<IComponent<any>>'.
              Type 'new () => import("/MY_REPO/node_modules/@ag-grid-community/client-side-row-model/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iComponent").IComponent<any>' is not assignable to type 'new () => import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iComponent").IComponent<any>'.
                Construct signature return types 'IComponent<any>' and 'IComponent<any>' are incompatible.
                  The types returned by 'init(...)' are incompatible between these types.
                    Type 'void | import("/MY_REPO/node_modules/@ag-grid-community/client-side-row-model/node_modules/@ag-grid-community/core/dist/cjs/utils/promise").AgPromise<void>' is not assignable to type 'void | import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/utils/promise").AgPromise<void>'.
                      Type 'AgPromise<void>' is not assignable to type 'void | AgPromise<void>'.
                        Type 'import("/MY_REPO/node_modules/@ag-grid-community/client-side-row-model/node_modules/@ag-grid-community/core/dist/cjs/utils/promise").AgPromise<void>' is not assignable to type 'import("/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/utils/promise").AgPromise<void>'.
                          Types have separate declarations of a private property 'status'.ts(2322)
```

**Expected behavior**

For above code to run without type errors. Provided that all the modules can follow the same `Module` interface I'd expect the module to remain as an interface as well.

**Please tell us about your environment:**

Mac OS X 11.1 (Big Sur)
Node.js 12.21.1

* **ag-Grid version:** 25.0.1

This is not an issue in version 25.0.0 and earlier. So something was introduced in version 25.0.1.

Notably version 25.0.1 of ag-grid Angular works fine with version 25.0.0 of remaining Ag-grid.

* **Browser:**

N/A - Browser not launched due to compilation errors in TypeScripts.

* **Language:** [TypeScript 4.1.3]
* **Framework:** [Angular 11.0.7]

EDIT:
Same code with latest Angular (11.1.1) in a Stackblitz that actually works: https://stackblitz.com/edit/ag-grid-angular-hello-world-w6o9q5?file=src/app/app.component.ts

**Comment by seanlandsman** [comment]
Are you perhaps using symlinks/lerna in your project?

**Comment by Koslun** [comment]
@seanlandsman 
No. We are using [@nrwl/nx ](https://github.com/nrwl/nx) which we could use to use things from other projects but in effect it's only wrapping two different projects. One Angular project and one e2e project using Cypress in the same repo. With our Angular project being the default which is built using the [Angular CLI](https://angular.io/cli).

We for instance do not share dependencies between the two different projects and are grabbing all dependencies directly from regular npm with an authentication token to get some private packages like ag-grid enterprise, font awesome and one of our own making.

**Comment by seanlandsman** [comment]
I've no real knowledge of @nrwl/nx but there looks to be some duplication or something going on

For example

```
/MY_REPO/node_modules/@ag-grid-community/client-side-row-model/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iModule").Module
```

is being compared to 

```
/MY_REPO/node_modules/@ag-grid-community/core/dist/cjs/interfaces/iModule").Module
```

Which I'd guess (again, it's just a guess) is the cause of the problem

I'd say you need to work out how you can specify where the core code is - for example in webpack you could do something like:

```
resolve: {
    alias: {
        '@ag-grid-community/core$': path.resolve(__dirname, 'node_modules/@ag-grid-community/core'),
```

or similar.

Note that this just a guess, but it looki

**Comment by Koslun** [comment]
@makinggoodsoftware 
Thanks for the response. It does indeed seem to be something with how it is exported and how that's all handled.

Still a bit unsure of the root cause and best way to solve it. I don't believe nrwl/nx in particular would be the cause though, rather something with Angular CLI itself if it's nothing to do with ag-grid.

In attempt to find the root cause I forked the stackblitz link for the simplest Angular use-case of ag-grid and evolved it to use the same module-based solution I'm using above: https://stackblitz.com/edit/ag-grid-angular-hello-world-w6o9q5?file=src/app/app.component.ts

With it I also used a slightly newer Angular version and after some initial issues which might have been due to stackblitz itself the referenced code does seem to work as intended. Will try this out in our own environment and see if I can get the same result with the slightly newer version of Angular. If so I'll close this issue and blame it on some Angular CLI or webpack bug.

**Comment by ssdhaliwal** [comment]
Having same issue; below is the package.json and error (Angular 11):

 Type 'import("E:/home/development/angular/csvgrid/node_modules/@ag-grid-com
munity/core/dist/cjs/interfaces/iModule").Module[]' is not assignable to type 'i
mport("E:/home/development/angular/csvgrid/node_modules/ag-grid-community/di
st/lib/interfaces/iModule").Module[]'.

{
  "name": "csvgrid",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --ssl --ssl-key certs/localhost.key  --ssl-cert certs/localhost.crt",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@ag-grid-community/all-modules": "^25.0.1",
    "@angular/animations": "~11.0.9",
    "@angular/cdk": "~11.0.3-sha-ce5d10a77",
    "@angular/common": "~11.0.9",
    "@angular/compiler": "~11.0.9",
    "@angular/core": "~11.0.9",
    "@angular/forms": "~11.0.9",
    "@angular/material": "~11.0.3-sha-ce5d10a77",
    "@angular/platform-browser": "~11.0.9",
    "@angular/platform-browser-dynamic": "~11.0.9",
    "@angular/router": "~11.0.9",
    "@types/crypto-js": "^4.0.1",
    "@types/lodash": "^4.14.168",
    "@types/underscore": "^1.10.24",
    "ag-grid-angular": "^25.0.1",
    "ag-grid-community": "^25.0.1",
    "crypto-js": "^4.0.0",
    "lodash": "^4.17.20",
    "ngx-color-picker": "^11.0.0",
    "papaparse": "^5.3.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "underscore": "^1.12.0",
    "xlsx": "^0.16.9",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.7",
    "@angular/cli": "~11.0.7",
    "@angular/compiler-cli": "~11.0.9",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}

**Comment by ssdhaliwal** [comment]
I had same problem with Angular 11; where the code worked in Angular 7.  In Angular 7, had both Package and Modules as per the example; reading above - now, I removed the modules from grid since I am using packages; the issue is gone.  Can I get some explanation on what changed? or why? for me to understand better - thank you.

**Comment by seanlandsman** [comment]
Nothing around how we do either packages or modules has changed since first introduced, so I'm afraid I can't provide a cause there.

If you can provide a repo of the issue using modules I'd be happy to help.

**Comment by n-batalha** [comment]
@seanlandsman @makinggoodsoftware I'm evaluating agGrid enterprise and I think I got the same issue, here's a reproducible example https://github.com/n-batalha/aggrid-bug-example

**Comment by seanlandsman** [comment]
@n-batalha you have a few problems in your repo:

- you're mixing packages (ie ag-grid-community) and modules (ie @ag-grid-community/xxx) - you can only use one type of import. In your case remove ag-grid-xxx and add @ag-grid-community/react (replacing the corresponding import)
- you need to specify the rowModelType as 'serverSide'
- you need to provide data a bit differently with serverSide
- you'll need to import the necessary CSS

I'd suggest you go through the follow docs:

https://www.ag-grid.com/documentation/react/getting-started/
https://www.ag-grid.com/documentation/react/packages-modules/
https://www.ag-grid.com/documentation/react/row-models/

**Comment by n-batalha** [comment]
@seanlandsman the css and server side thing you can ignore, I just did a quick example of it failing on the type (by copying my working server side backend). It "works" if removing `modules` and fails if including it`.

The package/module bit was the issue. If I may I'd suggest that the [Packages and Modules](https://www.ag-grid.com/documentation/react/packages-modules/) section shows up earlier in the docs, it's the 5th top level section and much after "getting started". I was looking for it and didn't expect it as late in the documentation, so just proceeded by example. Perhaps other users here did the same.

Thanks

**Comment by Koslun** [comment]
I finally found the issue I had. It had nothing to do with my specific framework or build environment as initially alleged. Instead the issue was how yarn resolved our ag-grid dependencies.

We pin our dependencies in our package.json to specific numbers, i.e. 25.0.0, 25.0.1 etc. While the ag-grid dependencies have direct dependencies using ranges for instance this could be found in our yarn.lock file:

```
 "@ag-grid-community/client-side-row-model@~25.0.0":
  version "25.0.0"
  resolved "https://registry.yarnpkg.com/@ag-grid-community/client-side-row-model/-/client-side-row-model-25.0.1.tgz#8c19e6cd1e144d9e1f5142c07702700aebbc7b5b"
  integrity sha512-IUrFnXQu4+V/CDzd4XckWoCpjD/y80BmWwJys9xqYdSeeW3SVBJ191m4P5iu0y2pTM+5boxrwoONFI+m7MGGzw==
  dependencies:
    "@ag-grid-community/core" "~25.0.0"
    
 "@ag-grid-community/client-side-row-model@25.0.1":
  version "25.0.1"
  resolved "https://registry.yarnpkg.com/@ag-grid-community/client-side-row-model/-/client-side-row-model-25.0.1.tgz#8c19e6cd1e144d9e1f5142c07702700aebbc7b5b"
  integrity sha512-IUrFnXQu4+V/CDzd4XckWoCpjD/y80BmWwJys9xqYdSeeW3SVBJ191m4P5iu0y2pTM+5boxrwoONFI+m7MGGzw==
  dependencies:
    "@ag-grid-community/core" "~25.0.0"    
```

Meaning we got duplicated dependencies, one 25.0.1 and one 25.0.0. This eventually meant our build process using them both somehow and thus getting the error I specified.

The quick-fix was to simply remove all dependencies and re-install them again. Which for instance instead of above produced this:

```
"@ag-grid-community/client-side-row-model@25.0.1", "@ag-grid-community/client-side-row-model@~25.0.0":
  version "25.0.1"
  resolved "https://registry.yarnpkg.com/@ag-grid-community/client-side-row-model/-/client-side-row-model-25.0.1.tgz#8c19e6cd1e144d9e1f5142c07702700aebbc7b5b"
  integrity sha512-IUrFnXQu4+V/CDzd4XckWoCpjD/y80BmWwJys9xqYdSeeW3SVBJ191m4P5iu0y2pTM+5boxrwoONFI+m7MGGzw==
  dependencies:
    "@ag-grid-community/core" "~25.0.0"
```

Another fix has been to remove both of these modules importing everything:
```
    "@ag-grid-community/all-modules": "25.0.1",
    "@ag-grid-enterprise/all-modules": "25.0.1",
```
As implied they were directly depending on other dependencies and making this issue even worse. It however does appear that the other directly imported modules also still do have these direct dependencies. I thus think that this will inevitably continue to appear from time to time depending on how yarn decides to resolve our dependencies.

I think it would be a better approach if the `all-modules` libraries directly imported all modules and remaining modules that had dependencies are written as `peerDependencies`. This is how at least most smaller libraries do it to avoid duplication.

@seanlandsman is there a reason why `dependencies` are used instead of `peerDependencies`? I would assume it's to make it slightly easier to setup for newbies but figure they can just use the `all-modules` packages anyway.

**Comment by makinggoodsoftware** [comment]
Hi,

Seeing how you have found the solution, I am going to close this issue, 

@Koslun it would be difficult to fully discuss the choices made in this area... Feel free to open a new ticket if this is causing you any issues though

Thanks for all the feedback!

**Comment by lwouis** [comment]
@makinggoodsoftware ag-grid install is broken with yarn. I tested a migration from v25.0.1 to v26.2.0, and as @Koslun shows above, ag-grid internal dependencies being loose breaks the build.

It's an out-of-the-box breakage, introduced in v26.2.0 as far as I can tell. You should fix this.

---

For other people coming here for a workaround, I was able to fix the issue by adding this to `package.json`:

```json
"resolutions": {
  "@ag-grid-community/core": "26.2.0",
  "@ag-grid-enterprise/core": "26.2.0"
}
```

This forces any transitive dependency to `@ag-grid-community/core@26.2.0` to resolve with exactly `26.2.0` instead of for example `26.2.1` which was the reason why it broke in my case.

**Comment by SamihIsHis** [comment]
Just wanted to add my experience to this as I had the same problem but a much simpler fix.

In my case the package-lock.json file had gotten into a state where there were incompatible dependencies across the ag-grid libraries. I think this was initially because I updated ag-grid community/enterprise to 33.x.x but left ag-charts-community at 10.x.x (the documentation states you need to upgrade to 11.x.x I just hadn't seen it yet.

Without going into too much detail, it's worth knowing that when npm encounters unresolvable dependencies on the same library like this, it will install separate versions so that all packages that use it can meet their dependency requirements. The tell-tale sign that this has happened is that you will see extra node_modules folders _**within**_ a package folder e.g. node_modules/ag-grid-community/**node_modules**/...

Node used to warn when this happens but in the version I'm currently using it doesn't seem to be.

 But regardless, the solution for me was to get all my ag-xxx versions in package.json aligned, then delete the package-lock.json file **AND* the node_modules folder and then run npm i.

After that all libs pointed to the same interfaces in one central package.
