### ISSUE TITLE
Error: Uncaught [TypeError: this.btFirst.insertAdjacentElement is not a function]

### ISSUE THREAD

**Issue by tainguyenbui** [ag-grid/ag-grid#3488]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
While performing component testing in a React Application,

Rendering an `AgGridReact` component with `render` function from [`react-testing-library`](https://github.com/testing-library/react-testing-library/) throws the following error:
```
Error: Uncaught [TypeError: this.btFirst.insertAdjacentElement is not a function]
```

**Expected behavior**
Component is rendered correctly without any error

**Please tell us about your environment:**
MacOS Catalina 10.15
IntelliJ
Yarn
TypeScript
@testing-library/jest-dom: 4.2.3
@testing-library/react: 9.3.2
ag-grid-community: 21.2.2
ag-grid-react: 21.2.2

* **ag-Grid version:** 21.2.2

* **Browser:**
Tests are run in the terminal `react-scripts test --watchAll`

* **Language:** TypeScript 3.5.3

It seems to be happening somewhere in:
```
at PaginationComp.Object.<anonymous>.PaginationComp.postConstruct (xxxxx/node_modules/ag-grid-community/dist/lib/rowModels/pagination/paginationComp.js:49:22)
```

**Comment by strichenko** [comment]
This happening to  me also 

MacOS Catalina 10.15
Webstorm
Npm, Node 10
"@types/jest": "20.0.2",    
"jest": "20.0.4",
"jest-preset-angular": "2.0.4",
ag-grid-community: 21.2.2
ag-grid-angular: 21.2.2
TypeScript 3.5.3

**Comment by bboydflo** [comment]
I get the exact same error

MacOS Catalina
VSCode 1.40
Npm, Node 10
"@types/jest": "20.0.1",
"jest": "24.9.0",
"@ag-grid-community/all-modules": "^22.0.0",
"@ag-grid-community/angular": "^22.0.0",
TypeScript 3.6.3

**Comment by davis4acca** [comment]
https://github.com/jsdom/jsdom/issues/1890

**Comment by gudurisaiteja** [comment]
Facing the same issue even after upgrading jsdom to v15.x

**Comment by sdaconceicao** [comment]
If you're using jest for your test runner, you'll need to upgrade by installing jest-environment-jsdom-fourteen, and adding the following to your jest.config
`  testEnvironment: 'jest-environment-jsdom-fourteen' `

**Comment by sscaff1** [comment]
If you're using create-react-app,

```
npm i -D jest-environment-jsdom-fourteen
```

then in your scripts:

```
"test": "react-scripts test --env=jsdom-fourteen",
```

**Comment by dsgriffin** [comment]
Tests pass with the solution provided above (thanks)! but get some console errors:

```
console.error node_modules/react-dom/cjs/react-dom.development.js:530
      Warning: An update to null inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
```

**Comment by rrsai** [comment]
I did something similar to @sscaff1 's approach above, just bumped to jest-environment-jsdom-sixteen.  So it still works.

**Comment by theprogrammerinyou** [comment]
It still doesn't work for me, tried jsdom-fouteen and sixteen but still getting the same error. 
Dev environment - ubuntu 20.04
node 12.18.3
npm 7.18.1
"@testing-library/jest-dom": "^5.14.1",
  "@testing-library/react": "^11.2.7",
  "@testing-library/user-event": "^13.1.9",
  "ag-grid-community": "^21.2.2",
  "ag-grid-react": "^21.2.2",
