### ISSUE TITLE
Could not resolve "prop-types"

### ISSUE THREAD

**Issue by shadoworion** [ag-grid/ag-grid#4913]
I'm submitting a bug report

AG Grid version: 27.0.0
React 17 (Vite)

Fatal error on app run after update from ag version 26.2.0 to 27.0.0:

```bash
✘ [ERROR] Could not resolve "prop-types"

    node_modules/@ag-grid-community/react/lib/shared/agGridColumn.js:26:45:
      26 │ const prop_types_1 = __importDefault(require("prop-types"));
         ╵                                              ~~~~~~~~~~~~

  You can mark the path "prop-types" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "prop-types"

    node_modules/@ag-grid-community/react/lib/legacy/agGridReactLegacy.js:15:45:
      15 │ const prop_types_1 = __importDefault(require("prop-types"));
         ╵                                              ~~~~~~~~~~~~

  You can mark the path "prop-types" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

error when starting dev server:
Error: Build failed with 2 errors:
node_modules/@ag-grid-community/react/lib/legacy/agGridReactLegacy.js:15:45: ERROR: Could not resolve "prop-types"
node_modules/@ag-grid-community/react/lib/shared/agGridColumn.js:26:45: ERROR: Could not resolve "prop-types"
    at failureErrorWithLog (/Users/daviddakhovich/Documents/Projects/Bloxtax/BloxUI/node_modules/esbuild/lib/main.js:1601:15)
    at /Users/daviddakhovich/Documents/Projects/Bloxtax/BloxUI/node_modules/esbuild/lib/main.js:1247:28
    at runOnEndCallbacks (/Users/daviddakhovich/Documents/Projects/Bloxtax/BloxUI/node_modules/esbuild/lib/main.js:1032:63)
    at buildResponseToResult (/Users/daviddakhovich/Documents/Projects/Bloxtax/BloxUI/node_modules/esbuild/lib/main.js:1245:7)
    at /Users/daviddakhovich/Documents/Projects/Bloxtax/BloxUI/node_modules/esbuild/lib/main.js:1354:14
    at /Users/daviddakhovich/Documents/Projects/Bloxtax/BloxUI/node_modules/esbuild/lib/main.js:664:9
    at handleIncomingPacket (/Users/daviddakhovich/Documents/Projects/Bloxtax/BloxUI/node_modules/esbuild/lib/main.js:761:9)
    at Socket.readFromStdout (/Users/daviddakhovich/Documents/Projects/Bloxtax/BloxUI/node_modules/esbuild/lib/main.js:631:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
```

The problem was resolved after installing prop-types module.

**Comment by rmc-software** [comment]
This has been patched in v27.0.1. Thanks for reporting this.
