### ISSUE TITLE
Errors when instantiating custom components in a detail grid (new in v27)

### ISSUE THREAD

**Issue by bpoole1989** [ag-grid/ag-grid#4924]
**I'm submitting a ...
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour. 
Error when attempting to use a custom renderer in detail grid cells:  "Class constructor i cannot be invoked without 'new'". 

The same renderer(s) are working fine in master rows. The is reproducible across multiple components and apps. Error does not manifest in versions before 27.0.0.

The origin of the error appears to be in AG Grid repo code (userComponentFactory.js) attempting to call init() on an instance it creates of a wrapper around the custom component class being supplied.

Custom editors also seem to not get placed in the DOM even though the cell can be switched to editing mode in the usual ways. Editors seem not to throw the error triggered by renderers.

My digging has turned up a pretty consistent refrain that the error has to do with Babel and/or Typescript transpiling of native ES6 classes to ES5. I've tried many of the suggested fixes on [this thread](https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne) 
and [this thread](https://stackoverflow.com/questions/50203369/class-constructor-cannot-be-invoked-without-new-typescript-with-commonjs/50203532#50203532), with no luck.

<img width="682" alt="Screen Shot 2022-02-17 at 10 29 18 PM" src="https://user-images.githubusercontent.com/55624907/154612834-a7830ec5-87c4-4ff6-b22e-83cdec49c765.png">

Expected behaviour. Custom components function in detail grids as they do in master row cells.

**Please tell us about your environment:**
Angular 13, VS Code, Chrome

* **AG Grid version:**
27.0.0

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36'

* **Language:** 
Typescript ES6

**Comment by makinggoodsoftware** [comment]
Hi guys,

Looking at this issue in our end, but we are not sure how to reproduce this, we looked at our examples and it all seems to be working fine, would you mind seeing if you can provide us with a reproducible scenario?

Thanks

**Comment by bpoole1989** [comment]
Here is an example, working from the example grid at the bottom of this Master/Detail docs page: https://www.ag-grid.com/angular-data-grid/master-detail-master-rows/#changing-dynamic-master-rows

I applied the existing custom renderer to a detail grid colDef, after changing the renderer's template to simply show some text. As you can see, the master row cells that are still using that renderer show my new text, and the detail grid cells for the custom renderer colDef are blank. In this case I'm not getting the error that I observe with custom renderers in my app's detail grids, but this behavior is similar to what I am observing with custom editors in detail grid cells, where there is no error but it simply isn't inserted in to the DOM. I assume the error I am seeing with renderers has the same root cause as the failure of other components to render.

I also tried in this plunkr to register the custom renderer component by name instead of by class in the usual way, using the gridOptions.components, with the same result.

My plunkr: https://plnkr.co/plunk/Wx6K6MN1RgbH77ba

And a screenshot:
<img width="1677" alt="Screen Shot 2022-02-22 at 9 47 23 AM" src="https://user-images.githubusercontent.com/55624907/155159058-e281817e-4710-452b-a461-35f4bd0ce4ae.png">

**Comment by agrt56** [comment]
I have encountered the same problem for detail grid configuration in ag-grid 27.0.0 and Angular 13 + Ivy:

CellRenderer:

    ERROR TypeError: Class constructor EditActionCellRendererComponent cannot be invoked without 'new'
    at Adapter.init (ag-grid-community.cjs.js:38494:38)
    at UserComponentFactory.initComponent (ag-grid-community.cjs.js:17895:26)
    at UserComponentFactory.newAgStackInstance (ag-grid-community.cjs.js:17865:33)
    at Object.newAgStackInstance (ag-grid-community.cjs.js:17787:60)
    at createCellRendererFunc (ag-grid-community.cjs.js:44882:48)
    at AnimationFrameService.executeFrame (ag-grid-community.cjs.js:38943:21)
    at timer (zone.js:2561:1)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25475:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    
 TooltipComponent:

    core.mjs:6485 ERROR TypeError: tooltipComp.getGui is not a function
    at CustomTooltipFeature.newTooltipComponentCallback (ag-grid-community.cjs.js:10219:32)
    at ag-grid-community.cjs.js:10006:25
    at new AgPromise (ag-grid-community.cjs.js:9981:9)
    at AgPromise.then (ag-grid-community.cjs.js:10004:16)
    at CustomTooltipFeature.showTooltip (ag-grid-community.cjs.js:10211:42)
    at timer (zone.js:2561:1)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25475:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)`

**Comment by havardthom** [comment]
Also experienced following error when migrating from ag-grid v26.2.0 to v27.0.0 (in a Vue application with vue v2.6.10):

```
TypeError: compInstance.getGui is not a function
at ToolPanelWrapper.setToolPanelComponent (toolPanelWrapper.js?195b:62:1)
at eval (promise.js?63c4:43:1)
at new AgPromise (promise.js?63c4:18:1)
at AgPromise.then (promise.js?63c4:41:1)
at ToolPanelWrapper.setToolPanelDef (toolPanelWrapper.js?195b:51:1)
at eval (sideBarComp.js?70c1:1:173:1)
at Array.forEach (<anonymous>)
at SideBarComp.setupToolPanels (SideBarComp.js?70c1:153:1)
at SideBarComp.setSideBarDef (SideBarComp.js?70c1:132:1)
at SideBarComp.postConstruct (SideBarComp.js?70c1:33:1)
```
This error appeared when renaming `gridOptions.frameworkComponents` to `gridOptions.components`. I fixed the error by moving the custom component registration from gridOptions to the `components` option in our `.vue` file, as described here: https://www.ag-grid.com/archive/26.2.0/vue-data-grid/components/#mixing-javascript-and-vue

So it seems a breaking change was left out from the v27.0.0 changelog:
`gridOptions.frameworkComponents` supports custom vue renderers.
`gridOptions.components` does not support custom vue renderers.

**Comment by havardthom** [comment]
Relating to my previous comment, when we can no longer use `frameworkComponents` to register custom vue components, there is no way to register vue components in master detail grids (https://www.ag-grid.com/vue-data-grid/master-detail-grids/).

`detailCellRendererParams.detailGridOptions.components` does not support vue components.
`detailCellRendererParams.detailGridOptions.frameworkComponents` is deprecated.
The vue component is not discovered if registered in the `component` option in `.vue` file.

See reproduced scenario: https://plnkr.co/edit/8IoXKpLsW3tHOA38

Vue component `testCellRenderer` is not found by master detail grid.
`AG Grid: Looking for component [testCellRenderer] but it wasn't found.`

**Comment by shuheb** [comment]
Hi @bpoole1989 @agrt56 @havardthom 

Thank you for reporting this - much appreciated!

We have added this bug to our backlog and we are tracking it with the following reference and description:

AG-6446 [Regression] When using master/detail with custom cell renderer in the detail grid, expanding a row throws an exception
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/
 
As a workaround for the meantime, you can supply your custom cell renderer through `frameworkComponents` (it's deprecated, but you can use it as a workaround):

See this implemented in the[ following plunkr
](https://plnkr.co/edit/92JWxVEOFHl8VfZq)

```
    detailGridOptions: {
      frameworkComponents: {
        SimpleCellRenderer,
      },
      columnDefs: [{ field: 'callId', cellRenderer: 'SimpleCellRenderer' }],
    },
```

Thanks again for raising this with us, note that we will soon close this issue as we've raised a bug for it.

**Comment by dean-g** [comment]
I am also getting the same error when I change the angular ag-grid version,
toolPanelFramework to toolPanel 
cellRendererFramework to cellRenderer

**Comment by makinggoodsoftware** [comment]
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Comment by Jitendra9548** [comment]
AG Grid Cell Renderers in Angular 9.1.0 is not working
Instead of showing value in the grid it is showing empty please help me on this issue!

**Comment by StephenCooper** [comment]
> AG Grid Cell Renderers in Angular 9.1.0 is not working Instead of showing value in the grid it is showing empty please help me on this issue!

@Jitendra9548 please raise a new issue including a reproduction of your issue including the Angular and AgGrid versions you are using. If you are using an older version of AG Grid check the archive for the accurate documentation. 

https://ag-grid.com/archive/
