### ISSUE TITLE
ag-grid-angular 27.1.0 not compatible with Angular 13.2.6

### ISSUE THREAD

**Issue by moberwasserlechner** [ag-grid/ag-grid#4973]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

I tried to upgrade to the latest version of `ag-grid-angular` 

```
    "ag-grid-angular": "27.1.0",
    "ag-grid-community": "27.1.0",
```

and on running `npm i` I get this

```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@1.0.0
npm ERR! Found: tslib@2.3.1
npm ERR! node_modules/tslib
npm ERR!   tslib@"2.3.1" from the root project
npm ERR!   tslib@"^2.3.0" from @angular/common@13.2.6
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"13.2.6" from the root project
npm ERR!     peer @angular/common@">= 8.0.0" from ag-grid-angular@27.1.0
npm ERR!     node_modules/ag-grid-angular
npm ERR!       ag-grid-angular@"27.1.0" from the root project
npm ERR!   2 more (@angular/core, zone.js)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer tslib@"^1.10.0" from ag-grid-angular@27.1.0
npm ERR! node_modules/ag-grid-angular
npm ERR!   ag-grid-angular@"27.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I rolled back to those versions and those are working with Angular `13.2.6`

```
    "ag-grid-angular": "27.0.0",
    "ag-grid-community": "27.0.1",
```

**Expected behavior**

**Please tell us about your environment:** Windows 10, git bash, npm

* **AG Grid version:** 27.1.0

* **Browser:** -

* **Language:** Typescript 4.5.5

**Comment by EmmanuelRoux** [comment]
Exact same problem here. Thanks for the workaround @moberwasserlechner

**Comment by AlexeyPotopakhin** [comment]
Angular 12.2.16 same behavior

**Comment by StephenCooper** [comment]
Thanks for reporting. I can reproduce this so we will take a look at what has caused tslib to move into peerDependencies as of 27.1

**Comment by isthar13** [comment]
I have been able to run `npm i` but Typescript complaints as it cannot find the Angular module of AgGrid: `Cannot find module '@ag-grid-community/angular' or its corresponding type declarations.ts(2307)`.

```
"dependencies": {
		"@ag-grid-community/angular": "~27.1.0",
		"@ag-grid-enterprise/all-modules": "~27.1.0",
		"@angular/animations": "~13.0.2",
		"@angular/common": "~13.0.2",
		"@angular/compiler": "~13.0.2",
		"@angular/core": "~13.0.2",
		"@angular/forms": "~13.0.2",
		"@angular/platform-browser": "~13.0.2",
		"@angular/platform-browser-dynamic": "~13.0.2",
		"@angular/router": "~13.0.2",
                ...
}
```

**Comment by StephenCooper** [comment]
We have released a patch version of `27.1.1`. This now works for me locally and should fix the issues mentioned in this ticket.

**Comment by moberwasserlechner** [comment]
@StephenCooper I have tested the patch and it works for me as well. Thanks.

**Comment by StephenCooper** [comment]
Thank you for confirming and apologies for the broken release this morning.
