### ISSUE TITLE
"Paste" does not work using Firefox browser (85.0.1 (64 bits))

### ISSUE THREAD

**Issue by MarionCrp** [ag-grid/ag-grid#4343]
Dear community and Support Team,

We cannot think about a spreadsheet table without paste functionnality for our customers. It seams the "Paste" functionnality does not work on Firefox browser. We are benchmarking ag-Grid before subscribing to an enterprise licence, and this is quite blocking. Thank you in advance. 

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
In Firefox (85.0.1 (64 bits)), the paste functionnality does not work. Tested also on your [demo example](https://www.ag-grid.com/example.php). Error displayed in the console is the following (Uncaught TypeError: navigator.clipboard.readText is not a function) :
![image](https://user-images.githubusercontent.com/15836199/107369320-ecebe300-6ae1-11eb-81f9-197df7b49485.png)

**Expected behavior**
I expect this "paste" functionality to work on all browsers. 

**Please tell us about your environment:**
macOS Catalina Version 10.15.7

* **ag-Grid version:** Enterprise v25.0.1 (using CDN)

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0

* **Language:** Vanilla JS

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shuheb** [comment]
Hi,

Thank you for raising this!

We are aware of this issue and have a bug fix in our backlog:

AG-4986 | [Regression] Pasting using ClipboardAPI doesn't work and throws an exception in Firefox

This is already fixed and for our next release next Friday (19th Feb).

Until this is resolved, we recommend temporarily revert to the old (pre-v25) Clipboard API by setting: suppressClipboardApi: true

This is demonstrated in this sample: https://plnkr.co/edit/lUD6gTYSlqPmlATA

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

We will close this ticket but please free to reopen the issue if it persists in the next release.

Thanks

**Comment by MarionCrp** [comment]
Thank you for your answers and your work ! Very nice to hear, the sample works like a charm :) ! 
Have a nice end of the week !
