### ISSUE TITLE
Dom exception occurs when editing data in custom cell editor then by clicking the next row or cell this error occurs

### ISSUE THREAD

**Issue by ajithanageswari** [ag-grid/ag-grid#3434]
core.js:6014 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at DefaultDomRenderer2.removeChild (http://localhost:4200/vendor.js:87491:20)
    at DebugRenderer2.removeChild (http://localhost:4200/vendor.js:76433:23)
    at execRenderNodeAction (http://localhost:4200/vendor.js:62040:22)
    at visitRenderNode (http://localhost:4200/vendor.js:62006:13)
    at visitSiblingRenderNodes (http://localhost:4200/vendor.js:61928:13)
    at visitRootRenderNodes (http://localhost:4200/vendor.js:61911:5)
    at renderDetachView$1 (http://localhost:4200/vendor.js:62595:5)
    at detachEmbeddedView (http://localhost:4200/vendor.js:62525:5)
    at ViewContainerRef_.detach (http://localhost:4200/vendor.js:62907:22)
    at ViewRef_.destroy (http://localhost:4200/vendor.js:62992:36)

**Comment by divinentd** [comment]
For me, the cause of this bug was that I was doing something in `onCellValueChanged` that altered what the result of `valueGetter` would be.

**Comment by skgattani** [comment]
after upgrading to ag grid 32.2.0 I see this issue, although it was working with ag grid 28.1.0
```
core.js:6014 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
at DefaultDomRenderer2.removeChild (http://localhost:4200/vendor.js:87491:20)
at DebugRenderer2.removeChild (http://localhost:4200/vendor.js:76433:23)
at execRenderNodeAction (http://localhost:4200/vendor.js:62040:22)
at visitRenderNode (http://localhost:4200/vendor.js:62006:13)
at visitSiblingRenderNodes (http://localhost:4200/vendor.js:61928:13)
at visitRootRenderNodes (http://localhost:4200/vendor.js:61911:5)
at renderDetachView$1 (http://localhost:4200/vendor.js:62595:5)
at detachEmbeddedView (http://localhost:4200/vendor.js:62525:5)
at ViewContainerRef_.detach (http://localhost:4200/vendor.js:62907:22)
at ViewRef_.destroy (http://localhost:4200/vendor.js:62992:36)
```

**Comment by skgattani** [comment]
> core.js:6014 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler? at DefaultDomRenderer2.removeChild (http://localhost:4200/vendor.js:87491:20) at DebugRenderer2.removeChild (http://localhost:4200/vendor.js:76433:23) at execRenderNodeAction (http://localhost:4200/vendor.js:62040:22) at visitRenderNode (http://localhost:4200/vendor.js:62006:13) at visitSiblingRenderNodes (http://localhost:4200/vendor.js:61928:13) at visitRootRenderNodes (http://localhost:4200/vendor.js:61911:5) at renderDetachView$1 (http://localhost:4200/vendor.js:62595:5) at detachEmbeddedView (http://localhost:4200/vendor.js:62525:5) at ViewContainerRef_.detach (http://localhost:4200/vendor.js:62907:22) at ViewRef_.destroy (http://localhost:4200/vendor.js:62992:36)

do you see any fix for this?
