### ISSUE TITLE
Does not build with angular 7 rc0 and typescript 3.1.1

### ISSUE THREAD

**Issue by zorrme** [ag-grid/ag-grid#2681]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
ERROR in node_modules/ag-grid-community/src/ts/gridPanel/rowDragFeature.ts(138,13): error TS2322: Type 'Timer' is not assignable to type 'number'.
node_modules/ag-grid-community/src/ts/headerRendering/moveColumnController.ts(345,13): error TS2322: Type 'Timer' is not assignable to type 'number'.
node_modules/ag-grid-community/src/ts/utils.ts(370,21): error TS1345: An expression of type 'void' cannot be tested for truthiness
node_modules/ag-grid-community/src/ts/utils.ts(1224,19): error TS2339: Property 'deepPath' does not exist on type 'Event'.
node_modules/ag-grid-community/src/ts/utils.ts(1226,26): error TS2339: Property 'deepPath' does not exist on type 'Event'.

**Expected behavior**
No build errors

**Please tell us about your environment:**
angular 7.0.0-rc.0
ag-grid-community 19.0.0

* **ag-Grid version:** 19.0.0

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.1.1

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by gportela85** [comment]
fixed in the latest branch

**Comment by zorrme** [comment]
When is it released ?

**Comment by MarkoCen** [comment]
I got same error after upgrade to ag-grid-community 19.1.1

```
ERROR in node_modules/ag-grid-community/src/ts/gridPanel/rowDragFeature.ts(138,13): error TS2322: Type 'Timer' is not
 assignable to type 'number'.
node_modules/ag-grid-community/src/ts/headerRendering/moveColumnController.ts(345,13): error TS2322: Type 'Timer' is
not assignable to type 'number'.
```

"typescript": "^3.1.3",
"@angular/animations": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/http": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
"@angular-devkit/build-angular": "^0.10.2",
    "@angular/cli": "^7.0.2",
    "@angular/compiler-cli": "^7.0.0",
    "@angular/language-service": "^7.0.0",

"ag-grid-angular": "^19.1.1",
"ag-grid-community": "^19.1.1",
"ag-grid-enterprise": "^19.1.1",

**Comment by zorrme** [comment]
Can you try "skipLibCheck": true in tsconfig.json

**Comment by MarkoCen** [comment]
@zorrme 
Thanks for the mention, the issue turns out is my bad, I accidentally imported `ValueFormatterParams`  directly from `ag-grid-community/src/ts/entities/colDef.ts`, which force tsc to compile ag-grid source code,

After changed the import path to `ag-grid-community`, everything works fine.

This issue was more on TypeScript side, `skipLibCheck` won't work if you import ts code from `node_modules` folder directly:

> **Why is a file in the exclude list still picked up by the compiler?**
>tsconfig.json turns a folder into a “project”. Without specifying any “exclude” or “files” entries, all files in the folder containing the tsconfig.json and all its sub-directories are included in your compilation.
>
> If you want to exclude some of the files use “exclude”, if you would rather specify all the files instead of letting the compiler look them up, use “files”.
>
> That was tsconfig.json automatic inclusion. There is a different issue, which is module resolution. By module resolution, I mean the compiler trying to understand what ns means in an import statement like: import * ns from “mod”. To do so, the compiler needs the definition of a module, this could be a .ts file for your own code, or a .d.ts for an imported definition files. if the file was found, it will be included regardless if it was excluded in the previous steps.
> 
> So to exclude a file from the compilation, you need to exclude and all all files that has an import or /// <reference path="..." /> directives to it.
> 
> Use tsc --listFiles to list what files are included in your compilation, and tsc --traceResolution to see why they were included.
