### ISSUE TITLE
v22.1.1 Could not find a declaration file for module './dist/ag-grid-enterprise.cjs.js'. 'xxxx/node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js' implicitly has an 'any' type

### ISSUE THREAD

**Issue by anna-kislovskaia** [ag-grid/ag-grid#3630]
v22.1.1 of ag-grid-entrerprise fails to compile with Typescript 3.7.4

Current behavior:
On attempt to run "tsc" error appears

```
 ../../node_modules/ag-grid-enterprise/main.d.ts(4,32): error TS7016: Could not find a declaration file for module './dist/ag-grid-enterprise.cjs.js'. XXX/node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js' implicitly has an 'any' type.
```

TS config
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "./lib",
    "module": "commonjs",
    "target": "es5",
    "lib": ["es6", "dom", "es2016", "es2017.object"],
    "sourceMap": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src/main",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "declaration": true
  }
}
```

Expected Behavior: 
Code compiles without issues

Ag-grid: 22.1.1
Language: Typescript 3.7.4

**Comment by baranovRP** [comment]
During update ag-grid-angular 21.2.2 -> 22.1.1 faced with the same issue

**Comment by AhmedAGadir** [comment]
Hi,

ag-grid staff does not provide support through github. If you are a customer please contact us through our official support channel. Note that this issue has been flagged as managed-by-the-community, we also recommend you to check stackoverflow, note that if there is no activity on this issue after a while we will close it.

Thanks

**Comment by anna-kislovskaia** [comment]
Workaround so far is to treat ag-grid-enterprise as untyped module

Extend tsconfig.json
```
{
  "compilerOptions": {
    "paths": {
      "ag-grid-enterprise": ["../../node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.cjs.js"]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./types"
    ]
  },
}
```

add typings for ag-grid-enterprise: create "types" folder in project root dir
```
types
|
___ ag-grid-enterprise
    |
    ___ index.d.ts
```

index.d.ts
```
declare module "ag-grid-enterprise";
```

**Comment by anna-kislovskaia** [comment]
Correct solution is to switch to modules as of https://www.ag-grid.com/javascript-grid-modules/

```
“dependencies” : {
"@ag-grid-enterprise/all-modules": "22.1.2",
"@ag-grid-community/react": "22.1.2",
}
```

**Comment by seanlandsman** [comment]
@anna-kislovskaia your workaround is an acceptable one, but `ag-grid-enterprise` missing types is a bug and covered by AG-3714. This will be fixed in our next release and the progress of the issue can be tracked in our pipeline here: https://www.ag-grid.com/ag-grid-pipeline/

thanks
