### ISSUE TITLE
TypeScript types cause strictNullChecks error on Ag-Grid-Community 19.1.1

### ISSUE THREAD

**Issue by amirburbea** [ag-grid/ag-grid#2740]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

Get this when compiling a project using ag-grid-community after updating to 19.1.1

My project built without issue on ag-grid-community 19.0.0

```
../../node_modules/ag-grid-community/dist/lib/exporter/xmlFactory.d.ts:17:5 - error TS2411: Property 'version' of type 'string | undefined' is not assignable to string index type 'string'.

17     version?: string;
       ~~~~~~~

../../node_modules/ag-grid-community/dist/lib/exporter/xmlFactory.d.ts:18:5 - error TS2411: Property 'standalone' of type 'string | undefined' is not assignable to string index type 'string'.

18     standalone?: string;
       ~~~~~~~~~~

../../node_modules/ag-grid-community/dist/lib/exporter/xmlFactory.d.ts:19:5 - error TS2411: Property 'encoding' of type 'string | undefined' is not assignable to string index type 'string'.

19     encoding?: string;
       ~~~~~~~~
```

The problem is that those three properties are in conflict with the line above it
```
export interface HeaderElement {
    [key: string]: string;
```

Changing the indexer to ``[key:string]: string|undefined;`` will solve the problem.

* **ag-Grid version:** 19.1.1

YES

* **Language:** TypeScript 3.1.4

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
The work to fix this is carried on AG-2259


AG-2259 TypeScript compiler error in xmlFactory.d.ts with strictNullChecks enabled



You can follow the status of feature requests, bugs and releases using our pipeline: 



https://www.ag-grid.com/ag-grid-pipeline/

(Note that newly raised issues can take up to 2 hours to appear in the pipeline)

**Comment by mrmckeb** [comment]
Hi @makinggoodsoftware, I can see that this has is an eight-day old issue - and it's currently affecting my team (we're working on a project where our client has licensed this component).

I can see a PR here there fixes the issue (#2741) that has been open for six days. Can you ask someone from your team to please approve/merge this PR and release an update?

**Comment by MatthewHerbst** [comment]
@mrmckeb they seem to have a lot of bug fixes done that haven't been released in a `9.1.2` yet - unclear what their release schedule is :(

**Comment by sousarka** [comment]
this is fixed in 19.1.2

**Comment by makinggoodsoftware** [comment]
Hi guys,

Yes, you should see this fixed in 19.1.2

:)
