### ISSUE TITLE
Getting error: react_dom_1.createPortal is not a function while providing React FrameworkComponents to AG-Grid enterprise -version 25.2.0

### ISSUE THREAD

**Issue by vinaybn27** [ag-grid/ag-grid#4474]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

I am evaluating the Enterprise version of AG-Grid. I am facing the below eeror:

On Providing the FrameworkComponents to <AgGridReact> with enterprise I am receiving the below error:

TypeError: react_dom_1.createPortal is not a function
    at NewReactComponent../node_modules/ag-grid-react/lib/newReactComponent.js.NewReactComponent.createOrUpdatePortal (bundle.min.js:106760)
    at NewReactComponent../node_modules/ag-grid-react/lib/newReactComponent.js.NewReactComponent.init (bundle.min.js:106747)
    at UserComponentFactory../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.UserComponentFactory.initComponent (bundle.min.js:24215)
    at UserComponentFactory../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.UserComponentFactory.createAndInitUserComponent (bundle.min.js:23970)
    at UserComponentFactory../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.UserComponentFactory.newHeaderComponent (bundle.min.js:23893)
    at HeaderWrapperComp../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.HeaderWrapperComp.appendHeaderComp (bundle.min.js:34907)
    at HeaderWrapperComp../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.HeaderWrapperComp.postConstruct (bundle.min.js:34735)
    at bundle.min.js:11028
    at Array.forEach (<anonymous>)
    at Context../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.Context.callLifeCycleMethodsOnBean (bundle.min.js:11028)

If I remove the FrameworkComponents. the grid is loading successfully. Please note that this was working with the ag-grid-react version 18.1.0

**Expected behavior**

The grid to be loaded with the Customized CellRender through Framework Components

**Please tell us about your environment:**

Windows 10, IntelliJ Idea, node-js, React Application

* **AG Grid version:** 25.2.0

* **Browser:**

Chrome, Edge

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] ES6

React Version: 15.5.4
React Dom: 15.5.4

**Comment by vinaybn27** [comment]
RCA of the issue with the React version. I did downgrade the ag-grid-enterprise to 18.1.2 and the functionality is intact. Hence closing this issue
