### ISSUE TITLE
 Uncaught TypeError: filterInstance.onFloatingFilterChanged is not a function

### ISSUE THREAD

**Issue by yshh1234** [ag-grid/ag-grid#7818]
**When I upgrade Ag from v26.0.0 to v30.2.1 find this error**

Current behaviour.
1. update  ag-grid-community ag-grid-enterprise ag-grid-vue modules from v26.0.0 to v30.2.1
2. use floatingFilter and type text into the floatFilter input
3. then show ' Uncaught TypeError: filterInstance.onFloatingFilterChanged is not a function'

**Expected behavior**

**Please tell us about your environment:**
win 11|chrome v123.0.6312.106|vue 2.6.12|node v16.20.0

* **AG Grid version:** 30.2.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

* **Language:** [all]

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
