### ISSUE TITLE
TypeError this.hidePopup is not a function

### ISSUE THREAD

**Issue by duxard** [ag-grid/ag-grid#4564]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I'm trying to implement a dropdown filter in Ag-Grid ("Floating filter")

Previously I was using the following code (in my dropdown column filter component):

```
hidePopup: any;

afterGuiAttached(params) {
   this.hidePopup = params.hidePopup;
}

....

closeFilter() {
 this.hidePopup();
}
```

But after updating Ag-grid to 24.1.0 version I noticed that "params" prop has become optional and now unavailable in afterGuiAttached():

```
 export interface  AgFrameworkComponent<T> {
  ....
  afterGuiAttached(params?: IAfterGuiAttachedParams): void
}
```

and therefore "params" are resolved now as "undefined". Therefore, when I'm trying to close the dropdown filter, it's triggering  this.hidePopup() method, which consequently appears to be undefined. That said, now when I'm trying to close the dropdown floating filter I get the following error in dev console:

**TypeError this.hidePopup is not a function**

Are the any suggestions on how I should use hidePopup() function (how to trigger closing of dropdown column filter?..

**Please tell us about your environment:**
Windows 10, Ag-grid 24.1.0

* **AG Grid version:** X.X.X
Ag-grid 24.1.0

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

* **Language:** [all | TypeScript 3.9.2 | ES6/7 ]
